VpcRecord:
  type: object
  properties:
    vpc_id:
      type: string
    resource_key:
      type: string
    name:
      type: string
    cidr:
      type: string
    updated_at:
      type: string
      format: date-time
