CognitoJwtAuthorizer:
  type: oauth2
  flows:
    implicit:
      authorizationUrl: ${cognito_issuer}
      scopes: {}
  x-amazon-apigateway-authorizer:
    type: jwt
    identitySource: $request.header.Authorization
    jwtConfiguration:
      issuer: ${cognito_issuer}
      audience:
        - ${cognito_client_id}
